httpserver:
    host: localhost
    port: 8000

logger:
    # level: info, debug, warn, error
    level: debug

storage:
    # type: memory, postgres
    type: memory
    conn: postgres://calendar:calendar@localhost:5432/calendar_db?sslmode=disable
    
    
