logger:
    # level: info, debug, warn, error
    level: debug

storage:
    #type: memory
    type: postgres
    conn: postgres://calendar:CalendarPswd@127.0.0.1:5417/calendar_db?sslmode=disable
    
rabbitmq:
    address: amqp://guest:guest@localhost:5672/